name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64
      - run: >-
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - run: >-
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version
      - run: >-
          pip install --constraint=.github/workflows/constraints.txt nox
          nox --version
      - run: nox --sessions tests-3.8 coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
