name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: >-
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - run: >-
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version
      - run: >-
          pip install --constraint=.github/workflows/constraints.txt nox
          nox --version
      - run: nox
